// Simple readable autogenerated password (you can harden later)
const genPassword = (prefix = "user") =>
  `${prefix}-${Math.random().toString(36).slice(2, 6)}${Math.floor(Math.random()*90+10)}`;

module.exports = { genPassword };
